apiVersion: v1
entries:
  drupal:
  - annotations:
      charts.openshift.io/description: Reusable Kubernetes and OpenShift environment
        for Drupal with Redis and MariaDB
      charts.openshift.io/name: Drupal
      charts.openshift.io/provider: Deutsche Digitale Bibliothek
      drupal-chart.dev/maintainer-company: Deutsche Nationalbibliothek
    apiVersion: v2
    appVersion: "11"
    created: "2026-08-17T13:37:03.390539485Z"
    description: Reusable Kubernetes and OpenShift environment for Drupal with Redis
      and MariaDB
    digest: 095bcb58cb75d2ef9cb10d880712f4dec16b409e67ddbbd16de260421e8d7416
    kubeVersion: '>=1.25.0-0'
    maintainers:
    - email: m.buechner@dnb.de
      name: Michael Büchner
      url: https://github.com/mbuechner
    name: drupal
    type: application
    urls:
    - https://mbuechner.github.io/ddbdrupal/helm/stable/drupal-0.1.1.tgz
    version: 0.1.1
generated: "2026-08-17T13:37:03.389132283Z"
