apiVersion: v1
entries:
  ddbdrupal:
  - annotations:
      charts.openshift.io/description: Reusable Kubernetes and OpenShift environment
        for Drupal with Redis and MariaDB
      charts.openshift.io/name: Drupal
      charts.openshift.io/provider: Deutsche Digitale Bibliothek
      drupal-chart.dev/maintainer-company: Deutsche Nationalbibliothek
    apiVersion: v2
    appVersion: "11"
    created: "2026-08-18T05:41:24.234522617Z"
    description: Reusable Kubernetes and OpenShift environment for Drupal with Redis
      and MariaDB
    digest: 59220af443d2eb556464d54d90283278c01d143d8729f2862e2308977497a3c7
    kubeVersion: '>=1.25.0-0'
    maintainers:
    - email: m.buechner@dnb.de
      name: Michael Büchner
      url: https://github.com/mbuechner
    name: ddbdrupal
    type: application
    urls:
    - https://mbuechner.github.io/ddbdrupal/helm/stable/ddbdrupal-0.1.3.tgz
    version: 0.1.3
  - annotations:
      charts.openshift.io/description: Reusable Kubernetes and OpenShift environment
        for Drupal with Redis and MariaDB
      charts.openshift.io/name: Drupal
      charts.openshift.io/provider: Deutsche Digitale Bibliothek
      drupal-chart.dev/maintainer-company: Deutsche Nationalbibliothek
    apiVersion: v2
    appVersion: "11"
    created: "2026-08-18T05:41:24.23315484Z"
    description: Reusable Kubernetes and OpenShift environment for Drupal with Redis
      and MariaDB
    digest: 4f2e1f7dcf31dbc165e34fb10a26064625f50cfbd3ad96ab7e13d985fa1d69f7
    kubeVersion: '>=1.25.0-0'
    maintainers:
    - email: m.buechner@dnb.de
      name: Michael Büchner
      url: https://github.com/mbuechner
    name: ddbdrupal
    type: application
    urls:
    - https://mbuechner.github.io/ddbdrupal/helm/stable/ddbdrupal-0.1.2.tgz
    version: 0.1.2
  - annotations:
      charts.openshift.io/description: Reusable Kubernetes and OpenShift environment
        for Drupal with Redis and MariaDB
      charts.openshift.io/name: Drupal
      charts.openshift.io/provider: Deutsche Digitale Bibliothek
      drupal-chart.dev/maintainer-company: Deutsche Nationalbibliothek
    apiVersion: v2
    appVersion: "11"
    created: "2026-08-18T05:41:24.231699002Z"
    description: Reusable Kubernetes and OpenShift environment for Drupal with Redis
      and MariaDB
    digest: 8f0a2dc8a2e3dd3bac6155c0dab4b12709d7eb92b62c04714be3da443584da36
    kubeVersion: '>=1.25.0-0'
    maintainers:
    - email: m.buechner@dnb.de
      name: Michael Büchner
      url: https://github.com/mbuechner
    name: ddbdrupal
    type: application
    urls:
    - https://mbuechner.github.io/ddbdrupal/helm/stable/ddbdrupal-0.1.1.tgz
    version: 0.1.1
  drupal:
  - annotations:
      charts.openshift.io/description: Reusable Kubernetes and OpenShift environment
        for Drupal with Redis and MariaDB
      charts.openshift.io/name: Drupal
      charts.openshift.io/provider: Deutsche Digitale Bibliothek
      drupal-chart.dev/maintainer-company: Deutsche Nationalbibliothek
    apiVersion: v2
    appVersion: "11"
    created: "2026-08-18T05:41:24.236840606Z"
    description: Reusable Kubernetes and OpenShift environment for Drupal with Redis
      and MariaDB
    digest: 095bcb58cb75d2ef9cb10d880712f4dec16b409e67ddbbd16de260421e8d7416
    kubeVersion: '>=1.25.0-0'
    maintainers:
    - email: m.buechner@dnb.de
      name: Michael Büchner
      url: https://github.com/mbuechner
    name: drupal
    type: application
    urls:
    - https://mbuechner.github.io/ddbdrupal/helm/stable/drupal-0.1.1.tgz
    version: 0.1.1
generated: "2026-08-18T05:41:24.230191175Z"
