{{- $name := include "drupal.drupalName" . -}}
{{- include "drupal.assertAvailable" (dict "root" . "apiVersion" "v1" "kind" "Secret" "name" $name "allowAdoption" true) }}
{{- $hashSalt := randAlphaNum 64 | b64enc -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $name -}}
{{- if $existing -}}
  {{- $hashSalt = (get (default (dict) $existing.data) "hash-salt") | default $hashSalt -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "drupal.labels" . | nindent 4 }}
    app.kubernetes.io/component: drupal
  annotations:
    {{- include "drupal.protectionAnnotations" . | nindent 4 }}
    helm.sh/resource-policy: keep
type: Opaque
immutable: true
data:
  hash-salt: {{ $hashSalt | quote }}
{{- end }}
