{{- if and .Values.drupal.smtp.password (not .Values.drupal.smtp.existingSecret) }}
{{- $name := printf "%s-smtp" (include "drupal.drupalName" .) -}}
{{- include "drupal.assertAvailable" (dict "root" . "apiVersion" "v1" "kind" "Secret" "name" $name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "drupal.labels" . | nindent 4 }}
    app.kubernetes.io/component: drupal
  annotations:
    {{- include "drupal.protectionAnnotations" . | nindent 4 }}
type: Opaque
stringData:
  SMTP_PASSWORD: {{ .Values.drupal.smtp.password | quote }}
{{- end }}
